### ISSUE TITLE
Custom echo commands

### ISSUE THREAD

**Issue by solenum** [godwhoa/oodle#22]
The ability to define custom commands in the config that respond with a set string would be nice, for example in the config:

~~~
custom_commands = [
    "source" = "Find my source here: https://github.com/godwhoa/oodle",
    "site" = "some other string"
] 
~~~

Which would then work in IRC like so:

~~~
exezin: .source
oodle: Find my source here: https://github.com/godwhoa/oodle
~~~

**Comment by godwhoa** [comment]
Implemented. Configuration looks like this:
```toml
[custom_commands]
".source" = "Find my source here: https://github.com/godwhoa/oodle"
".site" = "some other string"
```
